FROM python:3.9-slim

RUN apt-get update && apt-get install -y pandoc wkhtmltopdf && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /data

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY save_to_pdf.py .

ENTRYPOINT ["python", "save_to_pdf.py"]
