FROM python:3.11

RUN pip install --upgrade pip
RUN pip install numpy
RUN pip install scikit-learn
RUN pip install numpy
RUN pip install keras
RUN pip install pandas
RUN pip install tensorflow